### ISSUE TITLE
Fix missing allocations by using % given.

### ISSUE THREAD

**Issue by porames** [djay/covidthailand#15]
According to the raw data published by MOPH, Vaccine allocation data are separated by the manufacturers (Sinovac and Astrazeneca). However, the scraped data shows `Vac Allocated AstraZeneca 1 | 2 and  Vac Allocated Sinovac 1 | 2`. What is the difference between the two?

Also vaccine allocation data of every province is missing after 9th May 2021 .

Thanks.

* EDIT *

# Fixes
- Improve documentation in the readme about dose 1|2. Maybe better names?
- Add in Allocated 1|2 value calculated from the given %. (or using allocated where available?)

**Comment by pmdscully** [comment]
Hi @porames ,

`Vac Allocated AstraZeneca 1 | 2 and Vac Allocated Sinovac 1 | 2` are extracted from the table in the [9/5 MOPH PDF](https://ddc.moph.go.th/uploads/ckeditor2//files/Daily%20report%202021-05-09.pdf) (and earlier). I.e. pages 3,4,5,6. In that table structure, these items correspond directly. I think you will find your answer easily.

If I check [24/5 PDF](https://ddc.moph.go.th/uploads/ckeditor2//files/Daily%20report%202021-05-24.pdf), that table does not exist. Therefore, no data is populated.

The MOPH table data structures are regularly changing and therefore require work to collect the data from the new table format.

**Comment by porames** [comment]
I see. Would you consider adding total allocated vaccine data for every province (the 3rd and 4th column)? From what I have seen, this data is pretty much consistent.
![image](https://user-images.githubusercontent.com/11443387/119432749-13efbd00-bd3f-11eb-9858-b37493c91a0e.png)

**Comment by djay** [comment]
@porames "Vac Given %" is included in the data so you can work out the allocation from this. But it doesn't tell you which vaccine was allocated.
I'm curious what you are trying to work out? Maybe there is another graph I can add based on allocations?

**Comment by porames** [comment]
@djay 
I'm using the data to create a vaccination rollout tracking website [https://covid-19.researcherth.co/vaccination](https://covid-19.researcherth.co/vaccination) and I'm thinking about adding amount of vaccine each province has been allocated.

**Comment by djay** [comment]
@porames nice. 2025 :) Not exactly fair given the gov plan wasn't to have lots of vaccine until june but will be interesting to see the trajectory after june.
If you know python, any help keeping the scrapping working is appreciated. As @pmdscully said the vaccine reports change and I expect them to change more once more vaccines come available. I have some outstanding tasks for vaccine data like correcting the cumulative numbers that go backwards which would also be useful for someone to take on.
Also putting in an a total allocation based on the % might be helpful so the data is easier for everyone to process

**Comment by porames** [comment]
@djay I've added credit for you guys project in my website. Hope that's cool. Without your project, I would have been manually scraping data by hands haha.

**Comment by djay** [comment]
@porames the restructuring has been merged now. I'll reopen this and change it to adding allocations based on % as this would be a good first contribution.

**Comment by djay** [comment]
@porames looks like they are no longer giving any detail on vaccinations in their reports anymore. I'll close this now and we can reopen it now if they start reporting again
