### ISSUE TITLE
cannot run code locally because province names relies on datasource no longer available

### ISSUE THREAD

**Issue by porames** [djay/covidthailand#18]
The cases data from [https://covid19.th-stat.com/api/open/cases](https://covid19.th-stat.com/api/open/cases) which is used to build provinces data is currently down and causes error while scraping.
https://github.com/djay/covidthailand/blob/b61ac75b68b7134e2cb79081f7aafd22984424cf/covidthailand.py#L1279

*EDIT*
# proposed fix
1. [ ]  export all the current mapping to csv and commit. should be just Province->ProvinceEn mapping.
2. [ ] replace current sources with single import of local province_mapping.csv
3. [ ] remove old code (or move to unused function)
4. [ ] should health districts also be kept locally?

**Comment by pmdscully** [comment]
Ideally, only `/today` is needed (which is operational 25/5): - https://covid19.th-stat.com/api/open/today
After the first call to collect the complete dataset, then only the latest day is required. 

In fact, only `[NewCases,NewRecoveries,NewDeaths]` data are needed (which can be from another source or some key-in system), the other data columns are calculated.

**Comment by djay** [comment]
the code will use the cached version if it fails to get a new version so it will keep working

**Comment by porames** [comment]
since I don't have the cached file locally, where can I get it so I can test other functions?

**Comment by djay** [comment]
yeah in that case its a little hard.
I've considered the idea storing all the data in a seperate github repo you can checkout.
What you can do do is download the combined.csv and put it in a folder called api. Then set an env variable USE_CACHE_DATA=True. Then it will only get the data that left uncommented in the USE_CACHE_DATA section of scrape_and_combine. The rest will come from the combined.csv.
Actually now the plots use more csv's so you might need more.
Actually why do you need to run it at all? why not just get the data posted on the website?

**Comment by porames** [comment]
I'm trying to figure out how the scraping works by testing it locally so I can see what features I can contribute

**Comment by djay** [comment]
@porames awesome. I'd look at https://github.com/djay/covidthailand/pull/17 as that attempts to clean up the code a lot to make it easier to understand. Hopefully merged soon

**Comment by djay** [comment]
I'd say the easiest way to try it out is download all the csvs into the api dir and turn on USE_CACHE_DATA mode.

**Comment by djay** [comment]
On going, the cases dataset being missing is an issue because it is the only source of hospitalised over the whole timeline I believe. I don't think that was in the situation reports going back that far.
I'm not sure if it is a good idea or not to make the system keep working if certain datasets are missing. its a bit complex to workout now which data sources are overlapping and some data sources mask errors in harder to parse ones so it gets complex

**Comment by porames** [comment]
Can this dataset be used instead? [https://data.go.th/dataset/covid-19-daily]( https://data.go.th/dataset/covid-19-daily)

**Comment by djay** [comment]
@porames I just realised that the only reason I use that datasource is for province name matching.
I was considering replacing that anyway with my own local csv so that might be the best way to solve this.

**Comment by djay** [comment]
@porames I've created a fix, can you test it out https://github.com/djay/covidthailand/pull/20

**Comment by pmdscully** [comment]
@djay - I am finding the change in the title of this issue confusing. My comment above no longer makes any sense.

Perhaps  `province name matching relies on too many datasources (replace with local csv)` should open as a new issue. 

Perhaps, revert back to the old issue title.

@porames  issue is: `cannot run the code locally, because of missing data source`.

**Comment by pmdscully** [comment]
This prospective provinces dataset [discussed here](https://github.com/djay/covidthailand/pull/20#issuecomment-850868420) will remove the need for this data source.

The prospective dataset linked above, either achieves or enables:
- [x] export all the current mapping to csv. should be just Province->ProvinceEn mapping.
- [x] replace current sources with single import of local province_mapping.csv
- [ ] remove old code (or move to unused function)
- [x] should health districts also be kept locally? <- includes locally.

**Comment by djay** [comment]
@porames this was fixed so you can run it locally now
