### ISSUE TITLE
quicker to identity region (using minimap and consistent colours)

### ISSUE THREAD

**Issue by modiholodri** [djay/covidthailand#186]
Add a small map to all region plots so that it can be see easily where each region is. the plot shown below is just a sample and the image is not correct.

![positivity_region_3](https://user-images.githubusercontent.com/9023241/141683869-795d84d5-0cca-4aec-91b8-42c64840a81a.png)

Another map related discussion can be found in #168 Improve Legends.

**Comment by djay** [comment]
@modiholodri looks good but need all bright colours and also need map that separates out bangkok region correctly.
Would need colours that work well for both line and area plots like this 
![image](https://user-images.githubusercontent.com/41700/141724439-7b85663e-b260-435a-ab9d-36a5a7477606.png)

This is the list of named ones. I guess we can make a manual one if need be also?
https://matplotlib.org/stable/tutorials/colors/colormaps.html

**Comment by modiholodri** [comment]
I just downloaded the sample mini map, so it's not ok. The final one will have to correct provides according to the tables. Probably will have to map our own region cmap...
