### ISSUE TITLE
no data source for vaccinations details

### ISSUE THREAD

**Issue by djay** [djay/covidthailand#21]
the following is no longer in the report
- allocations
- per province risk groups or totals

All we have now is total + % for each shot of top 10 provinces vaccinated.

# Options
- find another source
- show by prvovince but with "rest of thailand" section. - remove other plots/exports

**Comment by djay** [comment]
Looks like I can continue the vaccination groups data if text similar to the following appears in each report going forward
> "จำกกำรติดตำมผลกำรให้บริกำรวัคซีนโควิด 19 ในระบบฐำนข้อมูล MOPH Immunization Center พบว่ำ ผู้ที่ได้รับวัคซีนสะสม ตั้งแต่วันที่ 28 กุมภำพันธ์ – 28 พฤษภำคม 2564 ทั้งหมด 3,504,125 โดส ใน 77 จังหวัดทั่วประเทศ ผู้ได้รับวัคซีนเข็มที่ 1 จำนวน 2,415,903 รำย เป็นบุคลำกรทำงกำรแพทย์ 814,623 รำย เจ้ำหน้ำที่ที่มีโอกำสสัมผัสผู้ป่วย 406,539 รำย ผู้ที่มีอำยุตั้งแต่ 60 ปีขึ้นไป 76,702 รำย บุคคลที่มีโรคประจำตัว 165,278 รำย ประชำชน ในพื้นที่เสี่ยง 952,761 รำย และจำนวนผู้ได้รับวัคซีนครบตำมเกณฑ์ (ได้รับวัคซีน 2 เข็ม) จำนวน 1,088,222 รำย เป็นบุคลำกรทำงกำรแพทย์ 596,228 รำย เจ้ำหน้ำที่ที่มีโอกำสสัมผัสผู้ป่วย 130,698 รำย ผู้ที่มีอำยุตั้งแต่ 60 ปี ขึ้นไป 2,881 รำย บุคคลที่มีโรคประจำตัว 55,569 รำย และประชำชนในพื้นที่เสี่ยง 302,846 รำย ดังรูป"

**Comment by djay** [comment]
Looks like top 10 province vaccinations is in 28th but not 29th so might not be consistent going forward.

> จังหวัดที่มีร้อยละควำมครอบคลุมกำรให้บริกำรวัคซีนโควิด 19 สูงสุด เทียบกับประชำกรรำยจังหวัด ตำมทะเบียนรำษฎร์และประชำกรแฝง 10 อันดับแรก ได้แก่ ภูเก็ต (เข็มที่ 1 ร้อยละ 43.75 และเข็มที่ 2 ร้อยละ 17.36) สมุทรสำคร (เข็มที่ 1 ร้อยละ 13.30 และเข็มที่ 2 ร้อยละ 10.25) ระนอง (เข็มที่ 1 ร้อยละ 8.37 และเข็มที่ 2 ร้อยละ 4.70) ตำก (เข็มที่ 1 ร้อยละ 8.31 และเข็มที่ 2 ร้อยละ 7.28) กรุงเทพมหำนคร (เข็มที่ 1 ร้อยละ 7.94 และเข็มที่ 2 ร้อยละ 2.55) นนทบุรี (เข็มที่ 1 ร้อยละ 6.01 และเข็มที่ 2 ร้อยละ 1.91) บุรีรัมย์ (เข็มที่ 1 ร้อยละ 5.48 และเข็มที่ 2 ร้อยละ 0.74) พังงำ (เข็มที่ 1 ร้อยละ 4.91 และเข็มที่ 2 ร้อยละ 2.52) ชลบุรี (เข็มที่ 1 ร้อยละ 4.42 และเข็มที่ 2 ร้อยละ 1.45) และ สุรำษฎร์ธำนี (เข็มที่ 1 ร้อยละ 4.36 และเข็มที่ 2 ร้อยละ 2.82) โดยมี ควำมครอบคลุมกำรให้บริกำรวัคซีนโควิด 19 ภำพรวมทั้งประเทศ เข็มที่ 1 ร้อยละ 2.84 และเข็มที่ 2 ร้อยละ 1.36

**Comment by chrisadas** [comment]
It's really a shame that per-province data was discontinued.

They could just publish raw numbers and save themselves the trouble of manually updating the charts each day. So many people willing to help, but no.

**Comment by djay** [comment]
They have no not uploaded any report in 2 days - https://ddc.moph.go.th/dcd/pagecontent.php?page=643&dept=dcd
Might need to find another source completely.
Good chance there will be something regulary in the daily briefing that gives at least some more details

**Comment by djay** [comment]
- Good news. I found where the reports are now - https://ddc.moph.go.th/vaccine-covid19/diaryReport
- Bad news. All the details are in graphics and the district graphs only show % against "target" without saying what the target/allocation is.

**Comment by chrisadas** [comment]
For what it's worth, this show the target number per group:

https://www.facebook.com/informationcovid19/photos/a.106455480972785/342985323986465/

- 712,000 for medical staffs
- 1,900,000 for frontline staffs
- 1,000,000 for village health volunteer (อาสาสมัครสาธารณสุขประจำหมู่บ้าน)
- 5,350,000 for risk: disease
- 12,500,000 for risk: over 60
- 28,538,000 for general population

Still can't find the target per province anywhere.

**Comment by djay** [comment]
Ah that's cool. Then I can show % complete for each group.
Per province doesn't matter because we no longer have updates for that.

**Comment by djay** [comment]
@porames I see you found another source for per province vaccinations? https://datastudio.google.com/u/0/reporting/731713b6-a3c4-4766-ab9d-a6502a4e7dd6/page/JMn3B

**Comment by porames** [comment]
> @porames I see you found another source for per province vaccinations? https://datastudio.google.com/u/0/reporting/731713b6-a3c4-4766-ab9d-a6502a4e7dd6/page/JMn3B

Yes. However, this source is updated sporadically and some vaccine counts are off by a bit, but I think it is the most completed and detailed dataset we currently have.

**Comment by porames** [comment]
@djay 
This is the request for getting the latest vaccination count for each province. 
https://github.com/porames/the-researcher-covid-bot/blob/c661daa787d17392b729b90fd16be9c1347e4398/bot_jobs/vaccination/fetch-MOPH-dashboard.js#L648

**Comment by djay** [comment]
@porames thanks for that. I wasn't able to get that query to work. I can't see it used in your code?
I was able to get some other queries working to get the timeseries. It would be nice however to get the _person_type_ breakdown per province like I had before, but haven't work that out yet, or at least the person_type timeseries.

**Comment by djay** [comment]
@porames from playing with it seems you can perhaps vary filters on a query but I haven't found out a way to get a different sort of count other than what has already be preset. Like getting counts per day per person_type. or dose1 dose2 per day per province.

**Comment by porames** [comment]
@djay If you go to "serial" section you will find information of every vaccination record (there are 3 million of them). You can find the query to pull that table and maybe process it from there. But this section was updated at 6th June.

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/11443387/121834923-220b7a80-ccfa-11eb-96f8-ce640d84c3b7.png">

**Comment by djay** [comment]
@porames yeah 3M/6 June is concern given the other vaccination views are up to 14th June. So might not be their base data so might be left no updated.
If I could just get 1 vs 2nd dose given per province I can put back my existing graphs :(

**Comment by djay** [comment]
@porames @pmdscully I've now put in the coldchain data for vaccines given per province. Just can't show dose 1 vs dose 2. These numbers don't match exactly unofficial numbers however
There is also downloadable data for delivered vaccine and I will add in imported vaccine also.
No breakdown of priority groups per province over time.

**Comment by djay** [comment]
oh and the reports are getting delayed :(

**Comment by djay** [comment]
wow 2021-07-02 report had the per prov dose 1 and dose 2 table in it. if it continues I might modify the old code to parse it.

**Comment by pmdscully** [comment]
> wow 2021-07-02 report had the per prov dose 1 and dose 2 table in it. if it continues I might modify the old code to parse it.

https://colab.research.google.com/drive/1COZBKKrXd8ekxMGRcDAYGUut7FDvqd7F?usp=sharing

**Comment by djay** [comment]
Thanks. I’ll add it to the list to do, or if you want to create a PR that would be great.
Given there is a massive gap in teh data it’s probably not that much use for my graphs since they are all trends over time so not in a hurry to add it. and they can always take it away again.

**Comment by pmdscully** [comment]
Okay. PR request point noted.

Hmm... I tested that Colab code on 4/7, 3/7 and 2/7. It falls over on 4/7, due to `Camelot` table parsing problem (8 columns vs 9 columns). It's probably best to re-write it using `Tika` magic, but some of the parsing procedure logic might be reusable. (Future work!)

**Comment by djay** [comment]
Everytime I try to use camelot I find it inconsistent. and if I can’t rely on it always getting the same tableeverytime  then I might as well have used text scraping instead which is what ends up happening. The only times I’ve ended up with camelot still in the code is historical formats that aren’t used anymore.
I suspect my existing code for the old tables won’t be hard to change to make it work for this new table since its so similar.

**Comment by porames** [comment]
@djay now it looks like [scraped vaccination data](https://raw.githubusercontent.com/wiki/djay/covidthailand/vac_timeline.csv) isn't updated, only vac delivery data is available.

**Comment by djay** [comment]
@porames Good catch. Thanks. It should be fixed now. 
I'll also close this issue and create a new one for any new vac sources

**Comment by djay** [comment]
@porames looks like the vac tracker is now completely locked up. So no source for vaccination imports.
And a big gap in my vaccination timeline if I lose my cache :(

**Comment by porames** [comment]
@djay hope our tracking project won't be ordered close with [the new information act](https://www.matichon.co.th/politics/news_2824430) haha

**Comment by djay** [comment]
@porames not a very helpful law that I think won't achieve what its stated intentions are.
Think I should request access?
