### ISSUE TITLE
Feature Request: Increase legend and title font sizes via rc.params

### ISSUE THREAD

**Issue by pmdscully** [djay/covidthailand#22]
### Problem:
Desktop viewers viewing on https://djay.github.io/covidthailand/ can zoom in or click to expand image sizes.
Desktop viewers viewing on https://github.com/djay/covidthailand/ cannot zoom in, as github css maintains image (/column) width.

This can make reading legends and title headings more difficult.

### Recommended Solution:
`matplotlib rc.params` default settings are around this line:
https://github.com/djay/covidthailand/blob/25fe9c54f12ca1470edbe333fbb947334ff86f4a/covid_plot.py#L170

Add / update `rc.params` for these items, until making those plots easily read at a quick glance ([rc-params-list](https://matplotlib.org/stable/api/matplotlib_configuration_api.html#matplotlib.RcParams)):
- legend.fontsize
- axes.titlesize
- figure.titlesize
- figure.titleweight

Then:
* Execute plot generating code. 
* Check plot headings / legends can be read more easily, yet still maintain good aesthetic appearance.

### Expected Outcomes:
- [ ] No warnings or error while running plot generating code.
- [ ] Plot Headings and Plot Legends are easily read "at a glance", while maintaining a good aesthetic appearance.

**Comment by djay** [comment]
Can increase most of them globally but legend size can't be increased for all since the area plots the legend will overlap the data. but that could be handled differently for those specific plots.

**Comment by pmdscully** [comment]
> Can increase most of them globally but legend size can't be increased for all since the area plots the legend will overlap the data (the current size was picked based on this). but that could be handled differently for those specific plots.

Okay fair enough. Matplotlib's `ax.legend( loc="best")` is usually pretty good.

Alternatives to increase the size without the overlap include:
1. to use `ax.legend( ....., loc='center left', bbox_to_anchor=(1.0, 0.5))` and position the legend outside the axis. (example positions right side of axis, but bottom might work well). [example](https://stackoverflow.com/a/4701285/1910555)
![image](https://user-images.githubusercontent.com/3637403/120194681-1de65400-c248-11eb-8d8f-8a66a8cc1acf.png)

2. arrow annotations with text label for each of the plotted lines. (e.g. `ax.patch( -> FancyArrowPatch)` and `ax.text`) [example](https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.FancyArrowPatch.html)
![image](https://user-images.githubusercontent.com/3637403/120194566-f7c0b400-c247-11eb-9afb-582aaad9cee7.png)

Any preferences?

**Comment by pmdscully** [comment]
The Plot titles and legends are easier to read now. 👍  I'll close this issue as done :-)
