### ISSUE TITLE
COVID-19 Data failed since 8 days ago

### ISSUE THREAD

**Issue by RuijingZ** [djay/covidthailand#272]
Hi,

The summary and brief COVID-19 data has not been out since 8 days ago. Will these dataset continuing updating in the future?
![image](https://user-images.githubusercontent.com/68354122/194944021-f02dc675-633b-4097-94a8-983f6d598bba.png)

Best,
Ruijing

**Comment by djay** [comment]
Since the 1st Oct gov reports only weekly data. I'm working on making the changes so the plots still work for this. But they are also reporting a much reduced set of numbers also so lots won't work any more

**Comment by djay** [comment]
@RuijingZ some of the data is back but it's now based on weekly averages
