### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by porames** [djay/covidthailand#33]
Since the official API for cases, deaths, hospitalization data ([https://covid19.th-stat.com/en/api](https://covid19.th-stat.com/en/api)) is unreliable: it's not regularly maintained and can't access from outside of Thailand (yep what the hell) which prevents server-side request; can you please add total death, cases and hospitalization numbers in the Daily Situation Reports?

**Comment by djay** [comment]
I think those numbers are already in there being parsed from the briefings. I guess I can also add the ones from the api since the briefings only go back to jan or so.

**Comment by djay** [comment]
Actually all those numbers are in combined.csv.
I guess I could create another export which is case/hospital/deaths stats from api, briefings and situation reports combined without all the other stuff in combined.csv? @porames

**Comment by porames** [comment]
@djay That would be great. Thanks!

**Comment by djay** [comment]
can you just use https://github.com/djay/covidthailand/wiki/combined.csv for now?

**Comment by porames** [comment]
I think I can work with that :)

**Comment by djay** [comment]
@porames I've simpllied the exports a bit so there is now a export just for these more basic stats from briefings (and the timeline.json). https://github.com/djay/covidthailand#daily-ccsa-briefings-
