### ISSUE TITLE
Use DDC vaccination report as provincial vaccination data source

### ISSUE THREAD

**Issue by porames** [djay/covidthailand#37]
Data from [COVID-19 Vaccines Track and Traceability Platform](https://datastudio.google.com/u/0/reporting/731713b6-a3c4-4766-ab9d-a6502a4e7dd6/page/vmmOC) is no longer reliable (I hope just for temporary). Meanwhile, DDC report now includes numbers for provincial vaccination. Perhaps you could modify the old code to scrape data from it.

**Comment by djay** [comment]
@porames I did this yesterday. But due #36 it hasn't run yet.

**Comment by djay** [comment]
fixed in https://github.com/djay/covidthailand/commit/f3f0e445d84be4101b294e0ebce442198b0bf6ac#diff-d421b480081e3d243e74357099a7e90eb2b5377e9dae2df4b4b6608605d97e14R562

**Comment by porames** [comment]
Data since July 7th is missing. <10,000 vaccinations reported, but the official count shows 300k+. Maybe someone is lying haha.
<img width="735" alt="image" src="https://user-images.githubusercontent.com/11443387/125231165-72c7c080-e304-11eb-8fe8-b732e5501f93.png">

**Comment by djay** [comment]
Sorry should have looked before asking :)
I've made a fix so the data from the reports should come through now. Plots look a little strange. Since the two sources don't agree previous not sure how they will combine.

**Comment by djay** [comment]
Data should be coming through now. But totals have gone backwards.
Is it better to have the raw values of both combined in that file? or do some cleaning to ensure it always increases? @porames 
![image](https://user-images.githubusercontent.com/41700/125237184-7a409700-e30f-11eb-9046-e76a847990f1.png)

**Comment by porames** [comment]
@djay So the data from cold chain platform doesn't match the DDC report?

**Comment by porames** [comment]
By the way, provinces data from the 3rd page of the report isn't available in your scraped file.

**Comment by djay** [comment]
@porames the daily totals didn't always add up the to same values.
I'll look at the scrapping issue. There should have been an assertion if not all provinces was included. Not sure why that didn't happen

**Comment by djay** [comment]
@porames it's getting the from all 77 provinces. Looks fine to me. Which data are you seeing missing?
BTW. I'll have to remove the "registrations" columns. I misunderstood it. It's just the province population

**Comment by porames** [comment]
07-11's data only shows 28 provinces but before that is looking ok
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11443387/125240741-b32f3a80-e314-11eb-836e-41305c4b7fc4.png">

**Comment by djay** [comment]
@porames There is no report for teh 11th yet. That data would be coming from the covid tracking source I think

**Comment by djay** [comment]
@porames I cut out that incomplete data in my code for my plots but I do it after I do the export to csv.
I will make it clearer by adding in a source field. Not sure if its a good idea to cut it out of the raw export though.
