### ISSUE TITLE
Plot nationality cases trends

### ISSUE THREAD

**Issue by djay** [djay/covidthailand#38]
Not that interesting but should be there.

**Comment by djay** [comment]
@andamanopal I'll close this one.
Looking at it again I think some improvements could be made. Could be stacked area and I wonder if it makes sense to show another one of all non-neighbour countries? or maybe just show more countries?

**Comment by andamanopal** [comment]
I think if individual countries only show insignificant number then we can group countries within the same continent (like NA, EU, etc.) and show the total number of each of those in addition to our neighbors countries (since the individual number of the latter would be equally large as the former)

**Comment by djay** [comment]
@andamanopal true. that would make it easier to see.
