### ISSUE TITLE
Question: would it be possible to get data on vaccine administered by brands?

### ISSUE THREAD

**Issue by nathakits** [djay/covidthailand#44]
From these MOPH daily slides on the 2nd page- https://ddc.moph.go.th/uploads/ckeditor2//files/Slide%202021-07-30.pdf

Example data
```json
{
    "date":"2021-07-04",
    "Sinovac_daily": 20170,
    "AstraZeneca_daily": 61284,
    "Sinopharm_daily": 17151,
    "AstraZeneca_total": 4061982,
    "Sinopharm_total": 95076,
    "Sinovac_total": 6513839
  },
  ```

The Researcher has already collect this type of data but it's incomplete with some dates missing some data.
https://github.com/porames/the-researcher-covid-bot/blob/master/components/gis/data/vaccine-manufacturer-timeseries.json

**Comment by nathakits** [comment]
Nevermind. I just saw that The Researcher was using  `vac_timeline.csv` file, which is missing the data.  Not sure, if it's possible but would be nice to have those missing data in the CSV.

I will close this task. 

Thank you for all the work that you've done!

**Comment by djay** [comment]
I'll see of I can fix it for the 30th.

**Comment by porames** [comment]
@nathakits Hi, The Researcher here. We are migrating vaccination by manufacturer data to use Moh Prompt dashboard instead. Will be completed soon.
https://github.com/porames/the-researcher-covid-data

**Comment by nathakits** [comment]
@porames cool! Looking forward to it!

**Comment by djay** [comment]
@nathakits Sorry this was added awhile back but I forgot to close the issue
