### ISSUE TITLE
Feature: 3rd dose data

### ISSUE THREAD

**Issue by nathakits** [djay/covidthailand#45]
Currently the daily reports doesn't include 3rd dose data but can be found with this link (as far as i know). Would be great to include this in the `vac_timeline` as well.

https://dashboard-vaccine.moph.go.th/

**Comment by djay** [comment]
@nathakits yeah I've seen that however it's not possible to get historical data and I curently don't do anything that requires storing values as I go. Waiting for it either to go into the report of the moph dashboard

**Comment by djay** [comment]
@nathakits it has been scraped here https://raw.githubusercontent.com/wiki/porames/the-researcher-covid-data/vaccination/provincial-vaccination.json by @porames

**Comment by nathakits** [comment]
@djay Thanks! Though what I'm looking for is a timeline. But at least this is something. You can close this task.

BTW I made a Twitter bot and a website, tracking the vaccinations. For the Twitter bot, I scraped everything myself, but for the website, I'm currently using my own data and yours `vac_timeline` as well.

https://twitter.com/THVaccinecount
http://covidtracker-th.netlify.app/

**Comment by djay** [comment]
@nathakits Looks nice. Thanks for the link.
If you know any python any help fixing the scraping of these reports is always welcome. You may notice it stops updating once and awhile

**Comment by nathakits** [comment]
Yeah I did notice that. 

I mostly code in JS. For Python, I only know some basic stuff so probably not going to be able to help much. I can take a look when I have time.
