### ISSUE TITLE
Vac Given by brands is gone?

### ISSUE THREAD

**Issue by nathakits** [djay/covidthailand#59]
Hi Dylan, I noticed that the "Vac Given  <brand>" is gone from the `vac_timeline.csv` file. Was it moved to another file or is this a bug? If this is a bug, I could try and help fix it.

Nat

**Comment by djay** [comment]
no I'm not sure why.

**Comment by djay** [comment]
There is a test for this and seems to be passing. Whats missing?
https://github.com/djay/covidthailand/blob/eb54ab9e86c948c07bc6f16f6fa93561553b09e3/tests/vac_manuf_given/1630646481545.2021-09-02.json

**Comment by nathakits** [comment]
Is it something to do with this? 

https://github.com/djay/covidthailand/runs/3509320672

**Comment by djay** [comment]
The error? Thats related to the situation reports and is unrelated.

**Comment by djay** [comment]
@nathakits this is the bug here https://github.com/djay/covidthailand/commit/f6bebcb75fbc32ca4331348cad81dec4c9abdeea#diff-d421b480081e3d243e74357099a7e90eb2b5377e9dae2df4b4b6608605d97e14R2981

**Comment by nathakits** [comment]
Glad you found it. I'm not sure what's wrong there 😆 Gotta start learning Python.

**Comment by djay** [comment]
Thanks for trying to help.
