### ISSUE TITLE
Add right side axis labels

### ISSUE THREAD

**Issue by modiholodri** [djay/covidthailand#73]
The most interesting data are on the right side of the chart. To have labels only on the left side makes it somehow hard to read.

![image](https://user-images.githubusercontent.com/9023241/134269375-27e49e8a-2fe4-42e9-b643-a4ac2ef4f681.png)

**Comment by djay** [comment]
@modiholodri really good idea. would be a one line change if you want to have a go and making a PR?

**Comment by modiholodri** [comment]
@djay Ok, I'll give it a try but might take a while because I never used Python so far and have to set up everything.  Have also a few more little improvements...

**Comment by djay** [comment]
@modiholodri the install is still a work in progress. hopefully this lastest update makes things clearer.
https://github.com/djay/covidthailand#running-just-plots-or-latest-files

**Comment by modiholodri** [comment]
@djay Just made the PR. Was my first one ever, so not sure how much I messed up...
