### ISSUE TITLE
Wrong COVID-19 Deaths risk at work on 09/23/2021

### ISSUE THREAD

**Issue by RuijingZ** [djay/covidthailand#80]
The data jumped to 89 for deaths risk work on 09/23/2021, while other historical data are all below 10. Would you mind confirming this outlier?

**Comment by djay** [comment]
Which plot data are you looking at? It seems the covid-19 data set hasn't been updated since 2021-09-20?
https://data.go.th/dataset/covid-19-daily
![image](https://user-images.githubusercontent.com/41700/134759133-d486ffb1-5495-4d73-b902-52b5149c3e14.png)

**Comment by RuijingZ** [comment]
> Which plot data are you looking at? It seems the covid-19 data set hasn't been updated since 2021-09-20?
> https://data.go.th/dataset/covid-19-daily
> ![image](https://user-images.githubusercontent.com/41700/134759133-d486ffb1-5495-4d73-b902-52b5149c3e14.png)

This is the file I looked at: https://raw.githubusercontent.com/wiki/djay/covidthailand/cases_briefings.csv
New COVID-19 deaths at work shows 89 on Sep 23 which is way larger than normal.

**Comment by reduxionist** [comment]
I will try to look into this the weekend after this. My apologies for the delay; we are currently backlogged, and I don't yet know where the deaths at work component of that csv file is drawn from as I am new to the codebase...

**Comment by djay** [comment]
@RuijingZ You can confirm this yourself as the url for the document that this data comes from is in the csv.
I had a quick look. it does look like its got the wrong number due to slightly different formatting.
<img width="1154" alt="Screen Shot 2021-09-29 at 11 44 19 am" src="https://user-images.githubusercontent.com/41700/135205044-154b1a19-13af-4a97-803c-257b0507dfe5.png">

**Comment by reduxionist** [comment]
@RuijingZ now that @djay has done the legwork for us, I will try to fix the scraping code to account for this variation in formatting the weekend after next... :smile:

**Comment by RuijingZ** [comment]
> @RuijingZ now that @djay has done the legwork for us, I will try to fix the scraping code to account for this variation in formatting the weekend after next... 😄

Thanks for letting me know! Now I got the Risk at work on Sep 23 2021 is supposed to be 0, not 89. However, could you help change this data accordingly in the csv file? It still shows 89: https://raw.githubusercontent.com/wiki/djay/covidthailand/cases_briefings.csv

I appreciate your help!

**Comment by reduxionist** [comment]
Hi @RuijingZ , I just issued a PR to fix this issue. We'll see if it passes the build, and then if so, once @djay is back online he will merge it promptly. Thanks again for bring out attention to the error! :wai: 八

**Comment by reduxionist** [comment]
Fixed by bbb58af.
