### ISSUE TITLE
Table of province cases in english

### ISSUE THREAD

**Issue by djay** [djay/covidthailand#81]
Since NTT stopped producing english province infographics people have been asking where to get them. Thaiger does some but tend to be late afternoon. Could be useful if we have an infographic with this list on it.

We could add it to the bottom of an existing plot (or smaller version of it).
For example 
![image](https://user-images.githubusercontent.com/41700/134759756-620f5027-c89b-4479-84f0-ae85ecce7142.png)

We could modify [topprov](https://github.com/djay/covidthailand/blob/main/utils_pandas.py#L259) to optionally return a dataframe with sorted provinces, the metric + a indication of change in rank (up 3 places etc). 

Then the [plot function](https://github.com/djay/covidthailand/blob/main/covid_plot.py#L21) could have another param called table to display an optional table of data. Similar to how the percent param adds an extra plot below. If it can be split over to table to save space then even better. Then we could add this table to several plots easily.

**Comment by modiholodri** [comment]
@djay Ok, just align it to me. I'll work on my issues in the order I prefer. If I should prioritize an issue just tell me...
