### ISSUE TITLE
7 day rolling average as % of peak

### ISSUE THREAD

**Issue by djay** [djay/covidthailand#87]
as on https://graphics.reuters.com/world-coronavirus-tracker-and-maps/vaccination-rollout-and-access/
![Screen Shot 2021-09-30 at 12 37 25 pm](https://user-images.githubusercontent.com/41700/135393614-d9f5d426-bee9-43cb-badb-55358a86ee3c.png)

original reason for the infections esitmate as a fairish way of showing the correlation between the deaths and cases. this is perhaps a better way of doing that. 
I think one plot could show
- tests
- cases
- severe cases
- ventilator
- deaths

Tests and cases should help show that it's not really the less you test the less cases you get.
The rest should help so if vaccinations are working (less severe cases per cases), or if testing is working (deaths/severe isn't more than cases).

Similar plot could be used to show mobility vs cases?

**Comment by djay** [comment]
also the infections estimate probably needs to be taken down. IFR becomes less and less accurate due to vaccinations and was probably not accurate with delta anyway.

**Comment by reduxionist** [comment]
woops referenced wrong issue in that unrelated commit.

anyway, just note to self: salving this issue would probably render #35 moot too.

**Comment by reduxionist** [comment]
# My notes based on guidance from @djay on how to implement this:

## Add to covid_plot.plot_area

### In func args

```python
          normalise_to_peak: bool = False
```

### In func doc string
```
    :param normalise_to_peak: whether to normalize data against peak value
```

### In func body
```
    if normalise_to_peak:
        df = df / df.loc[time_period].max()
```

+ magic?

**Comment by reduxionist** [comment]
I am moving along to #51 for now, so anyone who wants to dive in -- please feel free! :smiley:
